- name: Install Azure Data Studio
  become: yes
  become_user: root
  vars:
    azuredatastudio_version: '1.6.0'
  block:
    - name: Install Azure Data Studio
      apt:
        deb: "https://azuredatastudiobuilds.blob.core.windows.net/releases/{{azuredatastudio_version}}/azuredatastudio-linux-{{azuredatastudio_version}}.deb"

    - name: Configure persistent storage
      block:
        - name: Create persistent storage directories
          with_items:
            - azure-data-studio
            - azure-data-studio/user_home
            - azure-data-studio/user_config
          file:
            path: "/mnt/persistent_storage/{{item}}"
            state: directory
            owner: dev
            group: dev

        - name: Map user home config directory to persistent storage
          file:
            dest: /home/dev/.azuredatastudio
            src: /mnt/persistent_storage/azure-data-studio/user_home
            state: link

        - name: Map user config directory to persistent storage
          file:
            dest: /home/dev/.config/azuredatastudio
            src: /mnt/persistent_storage/azure-data-studio/user_config
            state: link
