- name: Install Azure Data Studio
  become: yes
  become_user: root
  vars:
    azuredatastudio_version: '1.6.0'
  apt:
    deb: "https://azuredatastudiobuilds.blob.core.windows.net/releases/{{azuredatastudio_version}}/azuredatastudio-linux-{{azuredatastudio_version}}.deb"

- name: Configure persistent storage
  with_items:
    - { folder_id: user_home, location: '/home/dev/.azuredatastudio' }
    - { folder_id: user_config, location: '/home/dev/.config/azuredatastudio' }
  loop_control:
    loop_var: persistent_storage
  include_role:
    name: persistent-storage
