- name: Install K3s
  become: yes
  become_user: root
  block:
    - name: Download k3s install script
      get_url:
        dest: /home/vagrant/k3s-install.sh
        url: https://raw.githubusercontent.com/rancher/k3s/master/install.sh
        mode: +x

    - name: Execute install script
      shell: /home/vagrant/k3s-install.sh

    - name: Enable and start k3s service
      service:
        name: k3s
        enabled: yes
        state: started

    - name: Change permissions on connection file
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: u=rw,g=r,o=r
