- hosts: all
  tasks:
    - name: Install Condement base
      import_role:
        name: condement-base
    - name: Install desktop
      import_role:
        name: "desktop-{{ os.desktop }}"
    - name: Install software
      loop: "{{ software | dict2items }}"
      loop_control:
        loop_var: software_item
        label: "{{ software_item.key }}"
      include_role:
        name: "software-{{ software_item.key }}"
