- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install Xubuntu desktop
      apt:
        name: xubuntu-desktop
        install_recommends: no
    - name: Install Whisker Menu
      package:
        name: xfce4-whiskermenu-plugin
    - name: Install standard gnome software package
      package:
        name: gnome-software